### ISSUE TITLE
Please explain plugin usefulness

### ISSUE THREAD

**Issue by pcav** [cempro/openatlasturkey#1]
In what is this different from simply adding a list of WFS/WMS?
Sorry to bother - we are trying hard not to multiply plugins unless necessary, to reduce confusion among users.
Thanks.

**Comment by cempro** [comment]
From the point of an experienced Qgis user there is nothing new. But there
are still many users who find it difficult to manage ogc services. They
usually ask me "do we write this service url into explorer?".

That's why I've written this small plugin (especially for Turkish users).
Plugin will auto. add all layers into map as layer group based on a
getcapabilities request. Besides service pool of this list plugin will be
updated periodically, more and more services will be added. I think these
will rationalize the plugin.

Thank you for your cooperation.
Cem


21 May 2017 11:12 tarihinde "Paolo Cavallini" <notifications@github.com>
yazdı:

In what is this different from simply adding a list of WFS/WMS?
Sorry to bother - we are trying hard not to multiply plugins unless
necessary, to reduce confusion among users.
Thanks.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/cempro/openatlasturkey/issues/1>, or mute the thread

**Comment by cempro** [comment]
OpenAtlasTurkey will neither be the first nor the last...  E.g. Indiana open data plugin or Greek open data plugin are already apporoved in the repo. Both developed with the similar intention; "easy access to country specific datasets." All services listed on OpenAtlasTurkey plugin are publically open to user access while some similar plugins need initial registration to add country datasets.

**Comment by pcav** [comment]
I think this can be done by Add WMS > Load list, that has been designed for this. I do not think this is much more difficult than installing a plugin. If you see a way of making it simpler, I think this would be an useful improvement for all.
Publishing it for now anyway.
Thanks.

**Comment by cempro** [comment]
Import capability a service pool list (csv, xml) would be great for the native qgis wms wfs windows. But thats beyond my capabilities, for qgis afaik this needs c++ knowledge. And thanks for your support.

**Comment by pcav** [comment]
This is already possible. If you missed that, this is a good explanation of this thread.

**Comment by cempro** [comment]
Thanks Paolo, I really missed that load button which was already there for a long time. 

By the way, I should edit existing service pool document to conform QGIS. (https://tucbs-public-api.csb.gov.tr/cografiveriservishavuzu/cografiveriservishavuzu.xml)

Let's keep the plugin in the repo for a while. 

May I close the issue if there is nothing else?

**Comment by pcav** [comment]
Glad I was not off track :)
Sure, let's close it. You could probably use profiles for QGIS3 instead of upgrading this one.
